version: '2'
services:
  mongo: 
    image: mongo
    volumes:
      - ./storage/mongodb:/data/db
    ports:
      - 27017:27017
      - 28017:28017
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./storage/redis:/data