version: '2.3'
services:
  mongo: 
    image: healthcheck/mongo
    ports:
      - 27017:27017
      - 28017:28017
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  frontend:
    image: ico-toolbox/frontend:0.1.0
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    depends_on:
      - user
      - payments
      - sale
    ports:
      - 80:80
    restart: on-failure
  user:
    image: ico-toolbox/user
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.user
    env_file: .env
    links:
      - mongo
      - redis
    depends_on:
      mongo:
        condition: service_healthy
    restart: on-failure
  payments:
    image: ico-toolbox/payments
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.payments
    env_file: .env
    links:
      - mongo
      - redis
    depends_on:
      mongo:
        condition: service_healthy
    restart: on-failure
  sale:
    image: ico-toolbox/sale
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.sale
    env_file: .env
    links:
      - mongo
      - redis
    depends_on:
      mongo:
        condition: service_healthy
    restart: on-failure